import type { EngineDefinition } from '../../types/engine';

/**
 * Synthetic engine used ONLY by unit tests (not shown in the app).
 * A generic 5.0 L cross-plane V8 with a 6-speed gearbox.
 */
export const testEngine: EngineDefinition = {
  id: 'chevrolet-zz632',
  manufacturer: 'Test',
  vehicle: 'Test Car',
  generation: 'T',
  year: 2020,
  marketVersion: 'test',
  isCrateEngine: false,
  headline: 'TEST V8',
  engine: {
    name: 'Test V8',
    code: 'T8',
    layout: 'v',
    cylinders: 8,
    bankAngleDeg: 90,
    displacementCc: 5000,
    boreMm: 94,
    strokeMm: 90,
    rodLengthMm: 155,
    rodLengthStatus: 'estimated',
    valvesPerCylinder: 4,
    valvetrain: 'dohc',
    aspiration: 'na',
    firingOrder: [1, 8, 4, 3, 6, 5, 7, 2],
    firingOrderStatus: 'official',
    cylinderMap: [
      { number: 1, row: 0, slot: 0 },
      { number: 3, row: 0, slot: 1 },
      { number: 5, row: 0, slot: 2 },
      { number: 7, row: 0, slot: 3 },
      { number: 2, row: 1, slot: 0 },
      { number: 4, row: 1, slot: 1 },
      { number: 6, row: 1, slot: 2 },
      { number: 8, row: 1, slot: 3 },
    ],
    crankType: 'cross-plane',
    lubrication: 'wet',
    fuelSystem: 'port injection',
    inertiaKgM2: 0.22,
  },
  performance: {
    powerPs: 450,
    powerHp: 444,
    powerKw: 331,
    powerRpm: 6500,
    torqueNm: 540,
    torqueRpm: 4500,
    idleRpm: 750,
    idleStatus: 'estimated',
    redlineRpm: 7000,
    revLimitRpm: 7200,
  },
  drivetrain: {
    transmission: '6-speed manual',
    kind: 'manual',
    ratios: [3.2, 2.2, 1.6, 1.25, 1.0, 0.8],
    reverseRatio: 3.0,
    finalDrive: 3.5,
    ratiosStatus: 'estimated',
    paddleShift: false,
    driveLayout: 'RWD',
    rearTire: '285/35 ZR19',
    tireRadiusM: 0.335,
    shiftTimeS: 0.4,
    efficiency: 0.88,
  },
  vehicleSpec: {
    topSpeedKmh: 250,
    topSpeedLimited: true,
    curbWeightKg: 1600,
    dragAreaM2: 0.7,
    rollingResistance: 0.013,
    fuelTankL: 70,
    fuelType: 'gasoline',
    enginePosition: 'front',
  },
  fuel: { capacityL: 70, capacityStatus: 'official', label: 'Tanque', fuelType: 'Gasolina' },
  dashboard: {
    style: 'crate',
    speedoMaxKmh: 300,
    speedoUnit: 'kmh',
    speedoMaxNative: 300,
    tachMaxRpm: 8000,
    tachRedlineStartRpm: 7000,
    hasShiftLights: false,
    reference: 'test',
  },
  soundProfile: 'v8-cross-bigblock',
  visual: { summary: 'test', accent: '#ff0000' },
  specs: [],
  sources: [],
  estimates: [],
};

export function withTurbo(def: EngineDefinition): EngineDefinition {
  return {
    ...def,
    engine: {
      ...def.engine,
      aspiration: 'turbo',
      turbo: {
        count: 2,
        arrangement: 'parallel',
        maxBoostBar: 1.0,
        maxBoostStatus: 'estimated',
        fullBoostRpm: 3500,
        spoolTimeS: 0.6,
        maxShaftRpm: 160000,
        feeds: [
          [1, 3, 5, 7],
          [2, 4, 6, 8],
        ],
      },
    },
  };
}
